baseURL = 'https://blog.med.schu.im/'
languageCode = 'en'
title = 'blog.med.schu.im'
theme = "about-blank"
enableGitInfo = true

[params]
  showTagPills = true

[markup.goldmark.renderer]
unsafe= true
